# SAM Template with correct CodeUri paths

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template to deploy Lambda functions and DynamoDB table for image generation and prompt optimization.

Parameters:
  S3BucketName:
    Type: String
    Default: creative360-datateam-image-generator-optimization
    Description: The S3 bucket where Lambda function code is stored.

Resources:
  # DynamoDB Table to save prompts
  SavedPromptsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SavedPrompts
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # IAM Role for Lambda Execution
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-LambdaExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                Resource: !GetAtt SavedPromptsTable.Arn
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: "*"

  # Lambda Function: ImageProcessingFunction
  ImageProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-ImageProcessingFunction"
      Handler: imageProcessing.lambda_handler
      Runtime: python3.11
      CodeUri: ../lambda_function/ImageProcessingFunction
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 120
      MemorySize: 1024

  # Lambda Function: SavePromptFunction
  SavePromptFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-SavePromptFunction"
      Handler: savePrompt.lambda_handler
      Runtime: python3.11
      CodeUri: ../lambda_function/SavePromptFunction
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 128

Outputs:
  # Output for the ImageProcessingFunction Lambda ARN
  ImageProcessingFunctionArn:
    Description: ARN of the Lambda function for image processing
    Value: !GetAtt ImageProcessingFunction.Arn

  # Output for the SavePromptFunction Lambda ARN
  SavePromptFunctionArn:
    Description: ARN of the Lambda function to save prompts
    Value: !GetAtt SavePromptFunction.Arn

  # Output for the DynamoDB Table ARN
  SavedPromptsTableArn:
    Description: The ARN of the DynamoDB Table for saved prompts
    Value: !GetAtt SavedPromptsTable.Arn